---
- name: Add repositories to sources.list
  become: true
  copy:
    dest: /etc/apt/sources.list
    content: |
      deb http://deb.debian.org/debian/ bookworm contrib main non-free non-free-firmware
      #deb-src http://deb.debian.org/debian/ bookworm contrib main non-free non-free-firmware

      deb http://deb.debian.org/debian/ bookworm-updates contrib main non-free non-free-firmware
      #deb-src http://deb.debian.org/debian/ bookworm-updates contrib main non-free non-free-firmware

      #deb http://deb.debian.org/debian/ bookworm-proposed-updates contrib main non-free non-free-firmware
      #deb-src http://deb.debian.org/debian/ bookworm-proposed-updates contrib main non-free non-free-firmware

      deb http://deb.debian.org/debian/ bookworm-backports contrib main non-free non-free-firmware
      #deb-src http://deb.debian.org/debian/ bookworm-backports contrib main non-free non-free-firmware

      deb http://deb.debian.org/debian-security/ bookworm-security contrib main non-free non-free-firmware
      #deb-src http://deb.debian.org/debian-security/ bookworm-security contrib main non-free non-free-firmware
  changed_when: false
  when: debian_nonfree | default(false) | bool
